name: Update README

on:
  push:
    paths:
      - '**/*.html'
      - '**/*.js'
      - '**/*.css'
    branches:
      - main

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Create/Update README
        run: |
          node .github/scripts/update-readme.js
        
      - name: Commit README changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git diff --quiet && git diff --staged --quiet || git commit -m "docs: Update README.md based on code changes"
          git push
